version: '3'

volumes:
  pg_data:
  static:
  media:

networks:
  kittygram_network:
    driver: bridge

services:
  gateway:
    image: valdmar918/kittygram_gateway
    container_name: gateway
    ports:
      - "80:80"
      - "8000:80"
    restart: always
    depends_on:
      - backend
      - frontend
    networks:
      - kittygram_network
    volumes:
      - static:/var/html/backend
      - media:/var/html/media
      - media:/app/media/
      - static:/var/html/static
  postgres:
    image: postgres:13
    container_name: postgres
    env_file: .env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - kittygram_network

  backend:
    image: valdmar918/kittygram_backend
    container_name: backend
    restart: always
    env_file: .env
    networks:
      - kittygram_network
    volumes:
      - static:/backend_static
      - media:/app/media/
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    image: valdmar918/kittygram_frontend
    container_name: frontend
    restart: always
    networks:
      - kittygram_network
    volumes:
      - static:/app/build